name: raahat_safety
description: Personal safety companion app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
  geolocator: ^12.0.0
  flutter_local_notifications: ^17.2.2
  android_alarm_manager_plus: ^4.0.4
  another_telephony: ^0.4.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
